import './globals.css'
import { Anek_Odia } from 'next/font/google'
import Navbar from './components/Navbar'

const inter = Anek_Odia({ subsets: ['latin'], weight: '600' })

export const metadata = {
  title: 'Syria-Turkey Earthquake',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-start">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}
